# action.yml
name: 'Generate Liquibase Changelog'
description: 'Executes Liquibase to Generate Postgres Changelog'
inputs:

  lbargs:
    description: liquibase arguments
    required: true
    default: "--username lbtest --password lbtest --url jdbc:postgresql://172.17.0.2:5432/postgres --changelog-file changelog.xml generatechangelog"

outputs:
  output: # Liquibase output
    description: 'Liquibase output'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lbargs }}
