# action.yml
name: 'Generate Liquibase Changelog'
description: 'Executes Liquibase to Generate Postgres Changelog'
inputs:

  username:
    description: postgres username
    required: true
    default: "--username lbtest"

  password:
    description: postgres password
    required: true
    default: "  --password lbtest"

  url:
    description: postgres url
    required: true
    default: "--url jdbc:postgresql://172.17.0.2:5432/postgres"

  changelog:
    description: liquibase changelog
    required: true
    default: "--changelog-file changelog.xml"

  generatechangelog:
    description: liquibase generatechangelog
    required: true
    default: "generatechangelog"

outputs:
  output: # Liquibase output
    description: 'Liquibase output'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.url }}
    - ${{ inputs.changelog }}
    - ${{ inputs.generatechangelog }}
